version: "3"
services:
  supabase-db:
    image: supabase/postgres:14
    container_name: supabase-db
    ports:
      - 7042:5432
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - supabase-db-data:/var/lib/postgresql/data

    # Backend Service
  api-backend:
    build:
      context: ./api-backend
      dockerfile: Dockerfile
    container_name: api-backend
    volumes:
      - .:/usr/src/app
    ports:
      - 3002:8080
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    depends_on:
      - supabase-db
      - user-frontend

  # Frontend Service
  user-frontend:
    build:
      context: ./user-frontend
      dockerfile: Dockerfile.dev
    container_name: nextjs-app
    ports:
      - 3001:3000
    command: yarn dev
    volumes:
      - ./frontend-service:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - api-backend

  # Load environment variables from .env.dev file
env_file:
  - .env.dev
