version: "3"
services:
  supabase-db-postgres:
    image: supabase/postgres
    platform: linux/amd64
    container_name: supabase-db-postgres
    ports:
      - 7032:5432
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    volumes:
      - supabase-data:/var/lib/postgresql/data
    env_file:
      - .env.dev

    # Backend Service
  api-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: api-backend
    volumes:
      - ./backend:/app
    ports:
      - 8010:8080
    environment:
      - OS_ENV=development
    depends_on:
      - supabase-db-postgres
    env_file:
      - ./backend/.env.dev

  # Frontend Service
  user-frontend:
    build:
      context: ./user-frontend
      dockerfile: Dockerfile.dev
    container_name: nextjs-app
    ports:
      - 3020:3000
    command: yarn dev
    volumes:
      - ./user-frontend:/app
      # - /app/node_modules
      - /app/.next
    depends_on:
      - api-backend
volumes:
  supabase-data:
