FROM golang:alpine AS builder
# Install git.
# Git is required for fetching the dependencies.
RUN apk update && apk add --no-cache 'git=~2'

# Install dependencies
ENV GO111MODULE=on
WORKDIR $GOPATH/src/packages/goginapp/
COPY . .

# Fetch dependencies.
# Using go get.
RUN go get -d -v

# Build the binary.
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /go/main .

FROM golang:alpine

ENV PROJECT_DIR=/app \
    GO111MODULE=on \
    CGO_ENABLED=0

WORKDIR /app

RUN go install github.com/githubnemo/CompileDaemon@latest
#RUN go install github.com/gin-gonic/gin@latest

COPY go.mod go.sum ./
RUN go mod download
#ENTRYPOINT CompileDaemon --build="go build main.go" --command=./main
# ENV BIN_APP_PORT=8080
COPY . .

# ENTRYPOINT CompileDaemon --build="go build main.go" --command=./main
CMD CompileDaemon --build="go build main.go" --command="./main"
