import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import ReactQueryClientProvider from "@/components/ReactQueryClientProvider";
import { Toaster } from "@/components/ui/sonner";
import NavHeader from "@/components/headerNav/NavHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ReactQueryClientProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <div className="max-w-screen flex w-screen h-screen flex-col">
              <div className="flex w-full flex-col">
                <NavHeader />
                {children}
              </div>
            </div>
            <Toaster richColors />
          </ThemeProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
